sudo: false
language: go
go:
  - 1.6
services:
  - redis-server
install:
  - go get github.com/satori/go.uuid
  - go get github.com/garyburd/redigo/redis
  - go get github.com/EverythingMe/disposable-redis
